let allPermissions = {};
export default allPermissions = {
  VIEW_MERCHANTS: 'VIEW_MERCHANTS',
  VIEW_PSP: 'VIEW_PSP',
  VIEW_PAYOUT_ACCOUNT: 'VIEW_PAYOUT_ACCOUNT',

  ADD_PSP: 'ADD_PSP',
  ADD_PAYOUT_ACCOUNT: 'ADD_PAYOUT_ACCOUNT',

  DELETE_MERCHANTS: 'DELETE_MERCHANTS',
  DELETE_PAYOUT_ACCOUNT: 'DELETE_PAYOUT_ACCOUNT',
  DELETE_PSP: 'DELETE_PSP',

  ALTER_PAYOUT_ACCOUNT: 'ALTER_PAYOUT_ACCOUNT',
  ALTER_PSP: ' ALTER_PSP',
  ALTER_SERVICE_SUBSCRIPTIONS: 'ALTER_SERVICE_SUBSCRIPTIONS',
  ALTER_API_CREDENTIALS: 'ALTER_API_CREDENTIALS',

  VIEW_ALL: 'VIEW_ALL',
  EDIT_ALL: 'EDIT_ALL',
  DELETE_ALL: 'DELETE_ALL',
};
